### PR TITLE
Fix 262 rss function

### LINKED ISSUE #262: Fix RSS function
Currently whenever RSS is invoked by any RSS tracker, rumors-site would print the following to log:

```
site-en_1       | 2020-06-10 08:59 +00:00: Error while running `getDataFromTree` ApolloError: GraphQL error: Variable "$filter" got invalid value "1" at "filter.replyRequestCount.GTE"; Int cannot represent non-integer value: "1"
site-en_1       |     at new ApolloError (/srv/www/node_modules/apollo-client/bundle.umd.js:92:26)
site-en_1       |     at /srv/www/node_modules/apollo-client/bundle.umd.js:1587:34
site-en_1       |     at /srv/www/node_modules/apollo-client/bundle.umd.js:2007:15
site-en_1       |     at Set.forEach (<anonymous>)
site-en_1       |     at /srv/www/node_modules/apollo-client/bundle.umd.js:2005:26
site-en_1       |     at Map.forEach (<anonymous>)
site-en_1       |     at QueryManager.broadcastQueries (/srv/www/node_modules/apollo-client/bundle.umd.js:2003:20)
site-en_1       |     at /srv/www/node_modules/apollo-client/bundle.umd.js:2130:19
site-en_1       |     at Object.next (/srv/www/node_modules/zen-observable/lib/Observable.js:308:23)
site-en_1       |     at notifySubscription (/srv/www/node_modules/zen-observable/lib/Observable.js:130:18) {
site-en_1       |   graphQLErrors: [
site-en_1       |     {
site-en_1       |       message: 'Variable "$filter" got invalid value "1" at "filter.replyRequestCount.GTE"; Int cannot represent non-integer value: "1"',
site-en_1       |       locations: [Array],
site-en_1       |       extensions: [Object],
site-en_1       |       authError: false
site-en_1       |     }
site-en_1       |   ],
site-en_1       |   networkError: null,
site-en_1       |   extraInfo: undefined
site-en_1       | }
site-en_1       | 2020-06-10 08:59 +00:00: [apollo-link-error] {
site-en_1       |   graphQLErrors: [
site-en_1       |     {
site-en_1       |       message: 'Variable "$filter" got invalid value "1" at "filter.replyRequestCount.GTE"; Int cannot represent non-integer value: "1"',
site-en_1       |       locations: [Array],
site-en_1       |       extensions: [Object],
site-en_1       |       authError: false
site-en_1       |     }
site-en_1       |   ],
site-en_1       |   response: { errors: [ [Object] ] },
site-en_1       |   operation: {
site-en_1       |     variables: { filter: [Object], orderBy: [Array] },
site-en_1       |     extensions: {},
site-en_1       |     operationName: 'ListArticles',
site-en_1       |     query: { kind: 'Document', definitions: [Array], loc: [Object] }
site-en_1       |   },
site-en_1       |   forward: [Function]
site-en_1       | }
site-en_1       | 2020-06-10 08:59 +00:00: [apollo-link-error] {
site-en_1       |   graphQLErrors: [
site-en_1       |     {
site-en_1       |       message: 'Variable "$filter" got invalid value "1" at "filter.replyRequestCount.GTE"; Int cannot represent non-integer value: "1"',
site-en_1       |       locations: [Array],
site-en_1       |       extensions: [Object],
site-en_1       |       authError: false
site-en_1       |     }
site-en_1       |   ],
site-en_1       |   response: { errors: [ [Object] ] },
site-en_1       |   operation: {
site-en_1       |     variables: { filter: [Object], orderBy: [Array] },
site-en_1       |     extensions: {},
site-en_1       |     operationName: 'ListArticlesStat',
site-en_1       |     query: { kind: 'Document', definitions: [Array], loc: [Object] }
site-en_1       |   },
site-en_1       |   forward: [Function]
site-en_1       | }

site-en_1       | 2020-06-10 09:02 +00:00: ApolloError: GraphQL error: Variable "$orderBy" got invalid value { undefined: "DESC" } at "orderBy[0]"; Field "undefined" is not defined by type "ListArticleOrderBy".
site-en_1       |     at new ApolloError (/srv/www/node_modules/apollo-client/bundle.umd.js:92:26)
site-en_1       |     at /srv/www/node_modules/apollo-client/bundle.umd.js:1587:34
site-en_1       |     at /srv/www/node_modules/apollo-client/bundle.umd.js:2007:15
site-en_1       |     at Set.forEach (<anonymous>)
site-en_1       |     at /srv/www/node_modules/apollo-client/bundle.umd.js:2005:26
site-en_1       |     at Map.forEach (<anonymous>)
site-en_1       |     at QueryManager.broadcastQueries (/srv/www/node_modules/apollo-client/bundle.umd.js:2003:20)
site-en_1       |     at /srv/www/node_modules/apollo-client/bundle.umd.js:2130:19
site-en_1       |     at Object.next (/srv/www/node_modules/zen-observable/lib/Observable.js:308:23)
site-en_1       |     at notifySubscription (/srv/www/node_modules/zen-observable/lib/Observable.js:130:18) {
site-en_1       |   graphQLErrors: [
site-en_1       |     {
site-en_1       |       message: 'Variable "$orderBy" got invalid value { undefined: "DESC" } at "orderBy[0]"; Field "undefined" is not defined by type "ListArticleOrderBy".',
site-en_1       |       locations: [Array],
site-en_1       |       extensions: [Object],
site-en_1       |       authError: false
site-en_1       |     }
site-en_1       |   ],
site-en_1       |   networkError: null,
site-en_1       |   extraInfo: undefined
site-en_1       | }
```

### PR DESCRIPTION
**Pull request by nonumpa**
Fixes #262 

feedUrl cannot handle options passed by ArticlePageLayout, so put option into query.

### CODE REVIEW

File: components/ArticlePageLayout.js [hunk 1]
```diff
@@ -227,7 +226,10 @@ function ArticlePageLayout({
     </mark>
   );
 
-  const queryString = querystring.stringify(query);
+  // if there's no repliedByMe in filter, we needn't userId field
+  if (!listQueryVars.articleRepliesFrom) delete queryWithOptions.userId;
+  const queryString = querystring.stringify(queryWithOptions);
```
Comment (MrOrz) [inline components/ArticlePageLayout.js:231]: I was thinking if we can directly convert `listQueryVars` to JSON and put them in feed URL. That should simplify `api/articles/[feed]` (because it don't need `getQueryVars`, just `JSON.parse`) and allows greater flexibility for streams.

What do you think @nonumpa ?

Comment (nonumpa) [reply components/ArticlePageLayout.js:231]: I also wanted to remove the dependency of `ArticlePageLayout.getQueryVars` from `api/articles/[feed]`, but it seems that it's not easy to directly convert `listQueryVars` to JSON.
螢幕快照 2020-08-05 下午6 01 23
I'm afraid that I should write a `listQueryVarsToJSON` function and another `getQueryVars` for `api/articles/[feed]`.

Comment (MrOrz) [reply components/ArticlePageLayout.js:231]: I was thinking a direct `JSON.stringify` should do the job :P
Is that too long for an URL?

Comment (nonumpa) [reply components/ArticlePageLayout.js:231]: Sorry, I mean querystring, not JSON.
Maybe I can encode filter and orderBy like [this](
https://stackoverflow.com/questions/41641426/passing-objects-as-url-parameters-c-sharp).
